# Generated by Django 5.1.4 on 2024-12-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
