# Generated by Django 5.1.4 on 2024-12-07 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabletime',
            options={'verbose_name_plural': 'Available Time'},
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'verbose_name_plural': 'Designation'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name_plural': 'Doctor'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name_plural': 'Specialization'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
