# Generated by Django 5.1.4 on 2024-12-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_doctor_user_doctor_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_time',
            field=models.ManyToManyField(blank=True, null=True, to='doctor.availabletime'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='designation',
            field=models.ManyToManyField(blank=True, null=True, to='doctor.designation'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor/images/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='meet_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.ManyToManyField(blank=True, null=True, to='doctor.specialization'),
        ),
    ]
